TomMelt/mdb

mdb/mdb_attach.py
mdb/mdb_shell.py

`uplot` is a command line tool that draw plots on the terminal.
This helps to keep the user in terminal and not breakout to a GUI from `matplotlib`. However, `matplotlib` is still available. And it could be beneficial to use `matplotlib` if the number of debug ranks (`-s`) is greater than e.g. 10.

add uplot (youplot) library for plotting variables

---

.readthedocs.yaml

readthedocs was not building mdb and as a result the API and click documentation could not be auto-generated.
This fixes the issue.

fix install of mdb in .readthedocs.yaml

---

mdb/mdb_shell.py

This can be used as a building block to add all sorts of custom commands to the gdb interactions. 
This PR implements the minimum needed to avoid users accidentally killing the GDB instance by quitting or EOF'ing whilst in an interaction, and instead simply ends the interaction returning the user to the MDB shell.
Some potential future use cases that could be added with this:
- interacting with a given process at a breakpoint, and within that interaction stepping all processes simultaneously (allows the user to e.g. keep TUI mode going whilst they are stepping through code)
- stepping a different process B whilst interacting with A to see how e.g. the MPI comms are sent/received by A
- quickly getting data from B whilst interacting with A without having to quit the interaction

Added stdin filter for `interact`

---

mdb/mdb_client.py
mdb/mdb_shell.py

Currently the debug processes can be closed but the user may not be notified. This can lead to them submitting commands that don't do anything with no feedback.
These changes to `mdb/mdb_client.py` and `mdb/mdb_shell.py` provide a warning when all debug processes `client.dbg_procs` are closed.
This may also pave the way for handling debug session restarts (pending a re-write of the `mdb launcher`).

Improve handling of closed debug processes

---

docs/source/quick-start.rst
mdb/mdb_shell.py
tests/test_integration.py

* add broadcast mode to mdb shell
* add broadcast mode to integration test
* add example to quickstart docs
Broadcast mode (bcm) sends commands to the selected ranks (see help select for more info). Broadcast mode is enabled/(disabled) by typing broadcast start/(stop). To exit broadcast mode, enter command [broadcast stop] or [quit] or press CTRL+D.
Example:
The following command will start broadcast mode.
(mdb) broadcast start

add broadcast mode

---

mdb/mdb_shell.py

fixes #14
* change regex in `do_command`
* add try/except to `do_interact`

improve error handling for typos in command and interact

---

docs/source/quick-start.rst
mdb/mdb_shell.py
tests/test_integration.py

output from `do_command` is now sorted in rank order.
I have updated the integration test and expanded the quickstart documentation.

sort output from do_command

---

mdb/async_client.py
tests/test_integration.py

I am able to reproduce the bug in the CI on my machine. I have no idea what is causing it, but I suspect a combination of race conditions and/or background processes, but I've at least made it terminate nicely now.
Part of this was also raising an exception when the asyncio error happens that was being infinitely repeated. I had previously missed that it occurred during connection, and not when sending a message.

Some CI test work

---

mdb/debug_client.py

Currently `ctrl+c` doesn't function properly. It should send interrupt to the running debug procs. Due to a bug that this PR fixes it was not executing the command properly.

Bugfix ctrl c

---

src/mdb/messages.py

fixes #45 
The `exchange_command_response` coming back from the exchange server is deserialized by `json.loads()`. This converts the dictionary from `{int: str}` to `{str: str}` which was ruining the sorting algorithm `sort_debug_response` in `utils.py`. This is resolved in this PR by manually converting the dictionary type for messages (`msg`) with type `msg["msg_type"] == exchange_command_response`

bug: fix ordering of output from debuggers

---

src/mdb/debug_client.py

remove temporary print statements from `debug_client.py`

chore: remove temporary print statements from debug_client.py

---

src/mdb/exchange_server.py

remove unused `listen` method from `AsyncExchangeServer`

chore: remove unused listen method from AsyncExchangeServer

---

docs/source/quick-start.rst

add example of target binary with args to docs
closes #41

docs: add example of target binary with args to docs

---

src/mdb/backend.py
src/mdb/debug_client.py
src/mdb/mdb_launch.py
src/mdb/mdb_wrapper.py

fixes #53 
allow user to redirect `stdout` of target program to a file.
User can specify the option `--redirect-stdout` in the mdb launcher (`mdb launch`)

feat: allow user to redirect stdout of target program

---

src/mdb/mdb_launch.py
src/mdb/mdb_wrapper.py

fixes #44 
fixes #31
allow user to override mpi config option name by setting `--mpi-config-opt`
For example, on systems that use cray mpi, the mpi config option is called `--config` or `--configfile`. To specify this use a `mdb launch` command like the following:
```
mdb launch -n 8 -t ./simple-mpi.exe --mpi-config-opt configfile
```

feat: allow user to override config option name

---

docs/source/quick-start.rst
src/mdb/exchange_server.py
src/mdb/mdb_attach.py
src/mdb/mdb_client.py
src/mdb/mdb_launch.py
src/mdb/mdb_shell.py
src/mdb/messages.py
tests/output/answer-gdb.stdout
tests/test_integration.py

this PR adds a useful status update to the `mdb launch` command so that users know when all the debuggers are successfully connected.
It looks something like this: 
```
$ mdb launch -n 64 -t ./simple-mpi.exe --mpi-command "mpirun --oversubscribe"                                                                                                                                                 
connecting to debuggers ... (64/64)                                                                                                                                                                                                                                                       
all debug clients connected
```
The count updates in real time and will display `(x/N)` where `x` is the number of connected …

feat: add debug client connection status to launcher

---

src/mdb/mdb_launch.py

Multinode support was never setup properly. It was due to a mishap that I confused `localhost` with the ip address of the host. So it would never be able to find the host IP address.
This PR fixes that issue and now it is possible to run multinode jobs.
`mdb launch` will now output handy connection info e.g.,:
```
running on host: 127.0.1.1
to connect to the debugger run:
mdb attach -h 127.0.1.1 -p 2000
```

bugfix fix support for multinode jobs

---

.github/workflows/code-validation.yml
.github/workflows/tests.yml

rename the github action job names. Both in `.github/workflows/code-validation.yml` and `.github/workflows/tests.yml` the status names were validation. In order to ensure both tests are required to pass (via branch protection rules) they have been renamed to `style` and `tests` respectively.

chore: update workflow files

---

src/mdb/debug_client.py
src/mdb/mdb_attach.py
src/mdb/mdb_shell.py

At some point the `Ctrl+C` functionality of `mdb` was lost. Having the ability to interrupt the target program (at any point) is essential for a debugger.
This PR restores this functionality :rocket:

bugfix: fix ctrl+c behaviour

---

CONTRIBUTING.md
src/mdb/backend.py
src/mdb/debug_client.py
src/mdb/mdb_shell.py
src/mdb/plugins/gdb.py
src/mdb/plugins/lldb.py

This PR adds a plugin-based debugger system to improve maintainability and extendability. Instead of hardcoding debuggers, they are now implemented as separate plugins inside the `src/mdb/plugins` directory.
- Introduced a plugin architecture for debugger backends.  
- Moved `gdb` and `lldb` implementations into separate plugin files.  
- Refactored core code to dynamically load debuggers instead of hardcoding them.  
- Updated documentation and added a short guide to `CONTRIBUTING.md` on how to add new debugger backends.
**To-Do:**
-  Ensure all tests pass on CI.
-  Refactor debugger backend tests to dynamically detect and test existing backends instead of hardcoding each. (Optional, as the current test setup also works.)

Add plugin-based debugger backend support, refactor gdb & lldb

---

src/mdb/async_connection.py
src/mdb/exchange_server.py
src/mdb/messages.py

fixes #76
This PR is responsible for replacing `END_BYTES = _MDB_END_` with exact `message length` sent from `send_message`.

Message header integration

---

examples/Makefile
examples/saxpy-mpi.cu
examples/simple-mpi-cuda.mdb
src/mdb/plugins/cuda-gdb.py

This PR adds support for the cuda-gdb backend.
- Added a cuda-gdb plugin.
- added an example CUDA program for testing cuda-gdb functionality (also updated Makefile to check for nvcc availability and build the CUDA program if available).
To-Do:
- Add tests for cuda-gdb (in the future, as there is no GPU support in CI and the current focus is on core functionality).

Add a plugin to support cuda-gdb

---

src/mdb/mdb_attach.py

Default the `hostname` when working on a single node.
If you are using a single node you can just type `mdb attach` rather than specify the hostname using `-h` or `--hostname`

feat: default hostname for attach
